name: Paradigmas - Orientação a Objetos e Funcional 🧪

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Execução
        uses: actions/setup-node@v4
        with:
          node-version: '19.x'
      - run: node oo.js
      - run: node functional.js