name: Paradigmas - Orientação a Objetos e Funcional 🧪

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: pacotes
      - run: rm -rf node_modules
      - run: npm install -g npm@latest
      - run: npm i core-util-is
      - uses: actions/checkout@v4
      - name: Paradigma de Orientação a Objetos
        uses: actions/setup-node@v4
        with:
          node-version: '19.x'
      - run: node oo.js

      - uses: actions/checkout@v4
      - name: Paradigma Funcional
        uses: actions/setup-node@v4
        with:
          node-version: '19.x'
      - run: node functional.js